# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12fe1e7608fb7c4ebf5fdf8aca0aa621be749247ce9f1752e2569fc6e543b7f3a692daaa839105a82ce2560a2beffdebfa228f503ac2cf09fa7eb10680f2192b

test:
  secret_key_base: 2c1b1542b1631676ef89608ad909756d7042da38796950b704ed08826f598cc3ee7897975346d083453b86b33c78467668ddef962b976b653ea5f69bbfafaf5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
